name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  unity-version:
    description: 'unity version'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - 'entrypoint.sh'
    - '${{ inputs.unity-version }}'
  env:
    UNITY_VERSION: ${{ inputs.unity-version }}

