name: 'Unity Editor Action'
description: 'A GitHub action to run Unity Editor on multi platform'
author: 'mob-sakai'
inputs:
  unity-version:
    description: '[Required] Version of Unity Editor to use.'
    required: true
  unity-modules:
    description: '[Optional] Modules of Unity Editor to use.'
    required: false
    default: ''
  project-path:
    description: '[Optional] Specify the relative path to your Unity project.'
    require: false
    default: '.'
  args:
    description: '[Optional] Specify the relative path to your Unity project.'
    require: false
    default: '-quit'
  secrets:
    description: '[Required] Secret json to activate Unity Editor.'
    require: false
    default: |
    '{
      ULF_WIN_2017: ${{ secret.ULF_WIN_2017 }},
      ULF_WIN_2018: ${{ secret.ULF_WIN_2018 }},
      ULF_WIN_2019: ${{ secret.ULF_WIN_2019 }},
      ULF_WIN_2020: ${{ secret.ULF_WIN_2020 }},
      ULF_WIN_2021: ${{ secret.ULF_WIN_2021 }},
      ULF_WIN_2022: ${{ secret.ULF_WIN_2022 }},

      ULF_OSX_2017: ${{ secret.ULF_OSX_2017 }},
      ULF_OSX_2018: ${{ secret.ULF_OSX_2018 }},
      ULF_OSX_2019: ${{ secret.ULF_OSX_2019 }},
      ULF_OSX_2020: ${{ secret.ULF_OSX_2020 }},
      ULF_OSX_2021: ${{ secret.ULF_OSX_2021 }},
      ULF_OSX_2022: ${{ secret.ULF_OSX_2022 }},
      
      ULF_LINUX_2017: ${{ secret.ULF_LINUX_2017 }},
      ULF_LINUX_2018: ${{ secret.ULF_LINUX_2018 }},
      ULF_LINUX_2019: ${{ secret.ULF_LINUX_2019 }},
      ULF_LINUX_2020: ${{ secret.ULF_LINUX_2020 }},
      ULF_LINUX_2021: ${{ secret.ULF_LINUX_2021 }},
      ULF_LINUX_2022: ${{ secret.ULF_LINUX_2022 }},
    }'
outputs: {}
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'box'
  color: 'gray-dark'