name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  unity-version:
    description: 'unity version'
    required: true
runs:
  using: 'entrypoint.sh'
  args:
    - '${{ inputs.unity-version }}'
