name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  unity-version:
    description: 'unity version'
    required: true
runs:
  using: docker
  image: 'docker://gableroux/unity3d:${{ inputs.unity-version }}'
  args:
    - 'entrypoint.sh'
    - '${{ inputs.unity-version }}'
