name: Create ALF File

on:
  push:
    branches:
      - '*'

  issues:
    types: [opened, reopened]
  pull_request:
    types: [opened, reopened, closed]

jobs:
  build:

    runs-on: ubuntu-latest
    container: docker://gableroux/unity3d:${{ matrix.unity-version }}
    strategy:
      matrix:
        unity-version: [2018.4.12f1]
    
    steps:
    - uses: actions/checkout@v1

    - name: Cache Unity License File
      id: cache
      uses: actions/cache@v1
      with:
        path: .ulf
        key: ${{ matrix.unity-version }}.ulf
        
    - name: Create Manual Activation File
      if: steps.cache.outputs.cache-hit != 'true'
      run: /opt/Unity/Editor/Unity -quit -batchmode -nographics -logfile -createManualActivationFile || exit 0

    - name: Setup node
      uses: actions/setup-node@v1.2.0
      with:
        node-version: 12

    - name: Activate Unity License File
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm i && node activate.js ${{ secrets.UNITY_USER_MAIL }} ${{ secrets.UNITY_USER_PASSWORD }} Unity_v${{ matrix.unity-version }}.alf

    - name: (OPTION)upload-artifact
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.unity-version }}
        path: Unity_v*.ulf

    - name: Move Unity License File To Cache
      if: steps.cache.outputs.cache-hit != 'true'
      run: mkdir .ulf && mv Unity_v*.ulf .ulf/ulf
