name: Create ALF File

on:
  issues:
    types: [opened, reopened]

jobs:
  build:

    runs-on: ubuntu-latest
    container: docker://gableroux/unity3d:${{ matrix.unity-version }}
    strategy:
      matrix:
        unity-version: [2018.4.12f1]
    
    steps:

    - name: Cache Alf
      id: cache-alf
      uses: actions/cache@v1
      with:
        path: artifact
        key: ${{ matrix.unity-version }}-primes
        
    - name: Create Manual Activation File
      if: steps.cache-alf.outputs.cache-hit != 'true'
      run: /opt/Unity/Editor/Unity -quit -batchmode -nographics -logfile -createManualActivationFile || exit 0

    - name: Copy To Artifact
      if: steps.cache-alf.outputs.cache-hit != 'true'
      run: |
        mkdir artifact
        cp Unity_v${{ matrix.unity-version }}.alf artifact
        