name: Create ALF File

on:
  push:
    branches:
      - '*'

  issues:
    types: [opened, reopened]
  pull_request:
    types: [opened, reopened, closed]

jobs:
  build:

    runs-on: ubuntu-latest
    container: docker://gableroux/unity3d:${{ matrix.unity-version }}
    strategy:
      matrix:
        unity-version: [2018.4.12f1]
    
    steps:
    - uses: actions/checkout@v1

    - name: Cache Alf
      id: cache-alf
      uses: actions/cache@v1
      with:
        path: artifact
        key: ${{ matrix.unity-version }}-alf
        
    - name: Create Manual Activation File
      if: steps.cache-alf.outputs.cache-hit != 'true'
      run: /opt/Unity/Editor/Unity -quit -batchmode -nographics -logfile -createManualActivationFile || exit 0

    - uses: actions/upload-artifact@v1
      with:
        name: Unity_v${{ matrix.unity-version }}.alf
        path: Unity_v${{ matrix.unity-version }}.alf

    - name: Activate
      run: npm i && node activate.js ${{ secrets.UNITY_USER_MAIL }} ${{ secrets.UNITY_USER_PASSWORD }} Unity_v${{ matrix.unity-version }}.alf

    - run: ls

    - name: Copy To Artifact
      if: steps.cache-alf.outputs.cache-hit != 'true'
      run: |
        mkdir artifact
        cp Unity_v${{ matrix.unity-version }}.alf artifact
        