name: Create ALF File

on:
  issues:
    types: [opened, reopened]


jobs:
  build:

    runs-on: ubuntu-latest
    container: docker://gableroux/unity3d:${{ github.event.issue.title }}-webgl
    
    steps:
    - name: Create Manual Activation File
      run: /opt/Unity/Editor/Unity -quit -batchmode -nographics -logfile -createManualActivationFile || exit 0

    - run: ls

    - uses: actions/upload-artifact@master
      with:
        name: artifact
        path: Unity_v${{ github.event.issue.title }}.alf

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.issue.title }}
        release_name: ${{ github.event.issue.title }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: artifact
        asset_name: ${{ github.event.issue.title }}.alf
        asset_content_type: application/text
    
    - name: Issue Comment
      uses: actions/github-script@0.2.0
      with:
        github-token: ${{ github.token }}
        script: |
          github.issues.createComment({...context.issue, body: '👋 Thanks for reporting!'})
