name: test_input

on:
  issues:
    types: [opened]

inputs:
  numOctocats:
    description: 'Number of Octocats'
    required: false
    default: '1'
  octocatEyeColor:
    description: 'Eye color of the Octocats'
    required: true

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: test input
      run: echo "${INPUT_NUMOCTOCATS} ${INPUT_OCTOCATEYECOLOR}"