name: Show alf

on: push

jobs:
  echo:
    runs-on: windows-latest
    strategy:
      matrix:
        unity-version: [2018.4.12f1]
    steps:
    - uses: pCYSl5EDgo/setup-unity@master
      with:
        unity-version: ${{ matrix.unity-version }}

    - run: "C:\\Program Files\\Unity\\Editor\\Unity.exe" -quit -batchMode -logFile -noGraphics -createManualActivationFile || exit /b 0
    - run: type Unity_v${{ matrix.unity-version }}.alf