name: test_input

on:
  issues:
    types: [opened]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: test input
        env:
          ISSUE_TITLE: ${{ github.event.payload.issue.title }}
        run: echo $ISSUE_TITLE