name: test

on:
  push:
    branches:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        unity-version: [2018.4.12f1]

    - name: Echo
      run: echo $secrets
      env:
        SEC: ${{ secrets.ULF_2017 }}

