name: test

on:
  push:
    branches:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        unity-version: [2018.4.12f1]

    steps:
      - name: Echo
        run: echo $secrets
        env:
          secrets: ${{ toJson(secrets) }}

