name: test

on:
  push:
    branches:
      - '*'
  # issues:
  #   types: [opened, reopened]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        unity-version: [2018.4.15f1]
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with: 
        ref: demo
        path: demo
    - uses: actions/setup-ruby@v1
      with: 
        ruby-version: 2.6.x
    - uses: ./
      with: 
        unity-version: ${{ matrix.unity-version }}
        secrets: ${{ toJson(secrets) }}
        project-path: 'demo'
        # args: 'hogehoge'
